name: ReportPlugin
main: com.example.reportplugin.ReportPlugin
version: 1.0
api-version: 1.21
author: Alone
commands:
  report:
    description: Report a player for rule-breaking.
    usage: /report <player> <reason>
    
